<?php
    
    define('TITANIA_FIRMWARE_MAJOR', "1");
    define('TITANIA_FIRMWARE_MINOR', "0");
    define('TITANIA_FIRMWARE_BUILD', "7");
    define('TITANIA_FIRMWARE_CHANNEL', "dev");

    define('TITANIA_FIRMWARE_VERSION', TITANIA_FIRMWARE_MAJOR . "." . TITANIA_FIRMWARE_MINOR . "." . TITANIA_FIRMWARE_BUILD . "-" . TITANIA_FIRMWARE_CHANNEL);
    define('TITANIA_FIRMWARE_DATE', "11/07/2014");
    
?>